services:
  maretanyar:
    container_name: maretanyar
    image: image_maretanyar
    build: .
    ports:
      - "8001:80"
    env_file:
      - .env
    networks:
      - my_network

networks:
  my_network:
    external: true
